name: "🚀 Feature Request"
description: Suggest new features or integrations
title: "[FEATURE]: "
labels: ["feature", "enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: What new capability?
      placeholder: "Describe the Feature capability"
    validations:
      required: true

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: As a [type of user], I want [goal], so that [benefit]
      placeholder: |
        As a [type of user],
        I want [goal],
        So that [benefit].

        Example:
        As a crypto trader,
        I want to set limit orders for token swaps,
        So that I can automate my trading strategy and not miss price targets.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why this feature?
      description: User need or competitor gap?
      placeholder: "Explain the problem this feature solves"
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation ideas
      description: APIs, libraries, rough approach?
      placeholder: "Any technical suggestions?"
    validations:
      required: false
